package com.ljdy.model;

import com.ljdy.model.base.BaseApplyinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Applyinfo extends BaseApplyinfo<Applyinfo> {
	public static final Applyinfo dao = new Applyinfo().dao();
}
