package com.ljdy.model;

import com.ljdy.model.base.BaseUser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public User validate(String username,String password){
		List<User> list = dao.find("select * from user where name = ? and password = ?",username,password);
		if (list.size() == 1){
			return list.get(0);
		}
		return null;
	}
}


