package com.ljdy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApplyinfo<M extends BaseApplyinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setOrganization(java.lang.String organization) {
		set("organization", organization);
		return (M)this;
	}

	public java.lang.String getOrganization() {
		return getStr("organization");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
		return (M)this;
	}

	public java.lang.String getPhoneNumber() {
		return getStr("phoneNumber");
	}

	public M setTextarea(java.lang.String textarea) {
		set("textarea", textarea);
		return (M)this;
	}

	public java.lang.String getTextarea() {
		return getStr("textarea");
	}

	public M setHostid(java.lang.String hostid) {
		set("hostid", hostid);
		return (M)this;
	}

	public java.lang.String getHostid() {
		return getStr("hostid");
	}

	public M setExtra(java.lang.String extra) {
		set("extra", extra);
		return (M)this;
	}

	public java.lang.String getExtra() {
		return getStr("extra");
	}

}
